### PR TITLE
Version 1 - File Download Added

### PR DESCRIPTION
**Pull request by aaronreay**
Hi, 

Having review Adams file upload code functionality, I have been able to produce the file retrieve from the database functionality.

Please find the code attached.

-Aaron

### CODE REVIEW

**Comment by Adam-Ellgood** [comment]
Hey Aaron, 

Thanks for sharing this, this looks great... any chance of just providing some commenting on your source code to get full understanding? 

Adam

**Comment by aaronreay** [comment]
Hi Adam, 

Apologies, please find the source code now commented. 

I was thinking, to have more modular code we could make use of the same database close connection rather than having 2 functions containing the same code. Perhaps we should suggest this when integrating the file upload and download. 

Cheers,

Aaron

**Comment by Adam-Ellgood** [comment]
Hi Aaron, 

Thank you, the code is more readable now it is commented! 

I had tested this on my local machine and with my local database and it retrieves an uploaded file perfectly,

I am glad my code assisted you with yours, it would definitely be great to bring both of these functionalities together now.

Creating the Jframe design has definitely assisted with the integration as we are now aware of the JFrame elements we both we require when bringing the code together as one. 

How would you like to do this? I have booked a room for us to bring the functionality together later today.

**Comment by aaronreay** [comment]
Hi Adam, 

I think it is great to meet up out of lab hours to integrate. 

I would like to have this nailed today if possible as we definitely have the potential to have these 2 functionalities integrated to help the team deliver as much of the functionality as possible. I think we should sit with the team then on inbedding our functionality with the master database. Therefore we can have 3 functionalities completed; login, file upload and file download.

This pull request can be closed now as it is considered a solution to the file download functionality. A new pull request can be set up to contain both the functionalities integrated together.

Cheers!

Aaron

**Pull request closed without merging**
